In [9]:
import numpy as np

f = np.loadtxt('minutes_n_ingredients.csv', delimiter=',',skiprows=1, dtype=np.int32)
print(f[:5,:])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


In [12]:
f1 = f[:,1:]
print('Среднее значение равно ',np.mean(f1,axis=0))
print('Минимум равен ',np.min(f1,axis=0))
print('Максимум равен ',np.max(f1,axis=0))
print('Медиана равна ',np.median(f1,axis=0))

Среднее значение равно  [2.16010017e+04 9.05528000e+00]
Минимум равен  [0 1]
Максимум равен  [2147483647         39]
Медиана равна  [40.  9.]


In [15]:
k = len(f[f[:,1]==0])
print(k) 
f[f[:,1]==0]=1

479


In [16]:
un = len(np.unique(f[:,0]))
print(un)

99522


In [21]:
l = len(np.unique(f[:,2]))
print(l)
print(np.unique(f[:,2]))

37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


In [22]:
f2 = f[f[:,2]<=5]
print(f2)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


In [36]:
sr = f[:,2]/f[:,1]
print(sr)
print(np.max(sr))

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
inf


<ipython-input-36-277dc4886424>:1: RuntimeWarning: divide by zero encountered in true_divide
  sr = f[:,2]/f[:,1]


In [23]:
a = f[f[:,1].argsort()]
a = a[-100:]
print(np.mean(a[:,2]))

6.61


In [24]:
index = np.random.choice(f.shape[0], 10, replace=False)
print(f[index])

[[132561     20     13]
 [ 42104     35      9]
 [309401     60      3]
 [111661     35     16]
 [ 52088     60      5]
 [376411     15     16]
 [452155     65      5]
 [282709     12      8]
 [ 25495     40      8]
 [249559     30     10]]


In [30]:
m = np.mean(f[:,2])
b = len(f[f[:,2]<m])
print(100*b/len(f))

58.802


In [34]:
new_f=f.copy()
simple = [1 if (row[1]<=20)and(row[2]<=5) else 0 for row in new_f]
c = np.insert(new_f,3,simple,axis=1)
print(c)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


In [35]:
simple1=c[:,3]==1
print(len(f[simple1,:])/len(c)*100)

9.552
